// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUdfwoUDhLxxO8WCyipE-OPj7yLymVl5A',
    appId: '1:637080344301:web:bcec3138c425baef59dee4',
    messagingSenderId: '637080344301',
    projectId: 'neurohealapp',
    authDomain: 'neurohealapp.firebaseapp.com',
    storageBucket: 'neurohealapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrtEl1iD7GJFv4KcZzMQtSUiGqeO79eJU',
    appId: '1:637080344301:android:b23d5d2d2e1f200259dee4',
    messagingSenderId: '637080344301',
    projectId: 'neurohealapp',
    storageBucket: 'neurohealapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGgljUxCMZO1eDk1fquEVviyGVVtRAGOk',
    appId: '1:637080344301:ios:e444444a262cae6f59dee4',
    messagingSenderId: '637080344301',
    projectId: 'neurohealapp',
    storageBucket: 'neurohealapp.firebasestorage.app',
    iosClientId: '637080344301-21c06as9joh8nbs9j9s73cc4vgnsraf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.neuroheal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGgljUxCMZO1eDk1fquEVviyGVVtRAGOk',
    appId: '1:637080344301:ios:e444444a262cae6f59dee4',
    messagingSenderId: '637080344301',
    projectId: 'neurohealapp',
    storageBucket: 'neurohealapp.firebasestorage.app',
    iosClientId: '637080344301-21c06as9joh8nbs9j9s73cc4vgnsraf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.neuroheal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUdfwoUDhLxxO8WCyipE-OPj7yLymVl5A',
    appId: '1:637080344301:web:724e1c2b508372ba59dee4',
    messagingSenderId: '637080344301',
    projectId: 'neurohealapp',
    authDomain: 'neurohealapp.firebaseapp.com',
    storageBucket: 'neurohealapp.firebasestorage.app',
  );
}
